# Generated by Django 3.2.5 on 2021-07-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
    ]
