# Generated by Django 3.2.5 on 2021-07-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_isdeleted_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='catalog.Catalog'),
        ),
    ]
