# Generated by Django 3.2.5 on 2021-07-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
